let one = 1;
let two = 2;
const add = one + two;
const multi = one * two;
const subtr = two - one;
const conca = String(one) + String(two);
two = 4;
const increment = one + 3;
const compare = one == two;
const lessthen = two < one;
const notEqual = one != two;
const lessOrgr = two < 10 & two > 0;